# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171007_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='FileField',
        ),
        migrations.RenameField(
            model_name='filefield',
            old_name='album_logo',
            new_name='file',
        ),
    ]
