# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acercaDe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integrantes',
            new_name='Integrante',
        ),
    ]
